In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

Data Collection

In [2]:
dataset=pd.read_csv('sales_revenu.csv',index_col=None)

dataset

,Store_ID,Product_ID,Product_Category,Store_Location,Day_of_Week,Holiday_Season,Discount_Percentage,Advertising_Spend,Customer_Rating,Weather,...,Loyalty_Customers_Percentage,Online_vs_Offline_Sales_Ratio,Average_Product_Age_days,Weekend_Sales_Percentage,Regional_Economy_Index,Store_Rent_Cost,Competitor_Discount_Percentage,Local_Events,Monthly_Inventory_Cost,Sales_Revenue
0,52,27,Furniture,Rural,Saturday,1,8.605530,13786.383758,3.544189,Rainy,...,28.065951,3.073859,155,39.976350,0.213137,18169.098197,23.415346,1,1042.007244,149827.170440
1,93,177,Toys,Rural,Tuesday,1,46.276110,18833.572229,2.607173,Cloudy,...,53.764897,4.396171,60,47.528238,0.884873,4919.622327,44.874994,0,49015.997618,116907.744138
2,15,161,Clothing,Suburban,Saturday,0,3.416705,1412.323977,3.311312,Cloudy,...,86.402261,0.920883,33,44.143278,0.981039,14265.684514,25.392504,0,20921.811170,42876.167811
3,72,98,Grocery,Rural,Sunday,0,21.518737,6733.215078,2.231497,Snowy,...,49.736490,1.111506,127,51.197903,0.020015,11284.925594,34.411402,0,26349.817087,120987.621577
4,61,105,Toys,Suburban,Saturday,1,34.789874,9044.445975,2.908800,Snowy,...,41.486226,4.755281,221,56.588937,0.546467,10967.831730,48.951468,0,10545.399910,152300.675075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,26,17,Clothing,Rural,Tuesday,1,38.678605,4745.394003,4.041313,Snowy,...,22.743687,9.593777,150,40.475661,0.249451,15433.598166,44.033044,1,22361.508371,102428.241511
796,63,14,Grocery,Suburban,Friday,1,2.202019,2218.967084,3.889646,Cloudy,...,39.774952,3.509969,118,42.602750,0.316594,4340.352878,13.056373,1,5241.998373,133566.267904
797,89,159,Electronics,Rural,Friday,0,34.666758,4293.433147,1.029568,Cloudy,...,63.821865,1.978811,165,48.808811,0.963041,12599.125478,4.754833,1,16085.301261,95861.855672
798,86,152,Electronics,Urban,Thursday,0,32.411795,16500.766715,3.036542,Snowy,...,83.965618,8.522007,252,63.520882,0.810154,15996.251584,6.845978,0,45115.294913,138804.928096
799,59,108,Electronics,Urban,Sunday,0,11.574005,13694.570379,1.557278,Snowy,...,75.317125,7.058703,267,39.574943,0.014086,17847.017507,39.640177,0,29152.136627,69191.622296

Data Preprocessing

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Store_ID                        800 non-null    int64
 1   Product_ID                      800 non-null    int64
 2   Product_Category                800 non-null    object
 3   Store_Location                  800 non-null    object
 4   Day_of_Week                     800 non-null    object
 5   Holiday_Season                  800 non-null    int64
 6   Discount_Percentage             800 non-null    float64
 7   Advertising_Spend               800 non-null    float64
 8   Customer_Rating                 800 non-null    float64
 9   Weather                         800 non-null    object
 10  Number_of_Employees             800 non-null    int64
 11  Store_Area_sqft                 800 non-null    int64
 12  Average_Transaction_Value       800 non-null    float64
 13  Number_of_Customers             800 non-null    int64
 14  Stock_Availability              800 non-null    float64
 15  Competitor_Proximity_km         800 non-null    float64
 16  Marketing_Channel               800 non-null    object
 17  Operating_Hours_per_Week        800 non-null    int64
 18  Store_Age_Years                 800 non-null    int64
 19  Price_Sensitivity               800 non-null    float64
 20  Loyalty_Customers_Percentage    800 non-null    float64
 21  Online_vs_Offline_Sales_Ratio   800 non-null    float64
 22  Average_Product_Age_days        800 non-null    int64
 23  Weekend_Sales_Percentage        800 non-null    float64
 24  Regional_Economy_Index          800 non-null    float64
 25  Store_Rent_Cost                 800 non-null    float64
 26  Competitor_Discount_Percentage  800 non-null    float64
 27  Local_Events                    800 non-null    int64
 28  Monthly_Inventory_Cost          800 non-null    float64
 29  Sales_Revenue                   800 non-null    float64
dtypes: float64(15), int64(10), object(5)
memory usage: 187.6+ KB

In [4]:
dataset.drop(['Store_ID','Product_ID','Day_of_Week'],axis=1,inplace=True)

In [5]:
dataset.isna().sum()

Product_Category                  0
Store_Location                    0
Holiday_Season                    0
Discount_Percentage               0
Advertising_Spend                 0
Customer_Rating                   0
Weather                           0
Number_of_Employees               0
Store_Area_sqft                   0
Average_Transaction_Value         0
Number_of_Customers               0
Stock_Availability                0
Competitor_Proximity_km           0
Marketing_Channel                 0
Operating_Hours_per_Week          0
Store_Age_Years                   0
Price_Sensitivity                 0
Loyalty_Customers_Percentage      0
Online_vs_Offline_Sales_Ratio     0
Average_Product_Age_days          0
Weekend_Sales_Percentage          0
Regional_Economy_Index            0
Store_Rent_Cost                   0
Competitor_Discount_Percentage    0
Local_Events                      0
Monthly_Inventory_Cost            0
Sales_Revenue                     0
dtype: int64

In [6]:
dataset.shape

(800, 27)

In [7]:
dataset[dataset.duplicated()]

Empty DataFrame
Columns: [Product_Category, Store_Location, Holiday_Season, Discount_Percentage, Advertising_Spend, Customer_Rating, Weather, Number_of_Employees, Store_Area_sqft, Average_Transaction_Value, Number_of_Customers, Stock_Availability, Competitor_Proximity_km, Marketing_Channel, Operating_Hours_per_Week, Store_Age_Years, Price_Sensitivity, Loyalty_Customers_Percentage, Online_vs_Offline_Sales_Ratio, Average_Product_Age_days, Weekend_Sales_Percentage, Regional_Economy_Index, Store_Rent_Cost, Competitor_Discount_Percentage, Local_Events, Monthly_Inventory_Cost, Sales_Revenue]
Index: []

[0 rows x 27 columns]

In [8]:
prep_df=dataset.copy()
prep_df.head()

,Product_Category,Store_Location,Holiday_Season,Discount_Percentage,Advertising_Spend,Customer_Rating,Weather,Number_of_Employees,Store_Area_sqft,Average_Transaction_Value,...,Loyalty_Customers_Percentage,Online_vs_Offline_Sales_Ratio,Average_Product_Age_days,Weekend_Sales_Percentage,Regional_Economy_Index,Store_Rent_Cost,Competitor_Discount_Percentage,Local_Events,Monthly_Inventory_Cost,Sales_Revenue
0,Furniture,Rural,1,8.605530,13786.383758,3.544189,Rainy,31,2458,271.677695,...,28.065951,3.073859,155,39.976350,0.213137,18169.098197,23.415346,1,1042.007244,149827.170440
1,Toys,Rural,1,46.276110,18833.572229,2.607173,Cloudy,44,4509,440.936720,...,53.764897,4.396171,60,47.528238,0.884873,4919.622327,44.874994,0,49015.997618,116907.744138
2,Clothing,Suburban,0,3.416705,1412.323977,3.311312,Cloudy,36,3235,210.911656,...,86.402261,0.920883,33,44.143278,0.981039,14265.684514,25.392504,0,20921.811170,42876.167811
3,Grocery,Rural,0,21.518737,6733.215078,2.231497,Snowy,30,4991,246.177510,...,49.736490,1.111506,127,51.197903,0.020015,11284.925594,34.411402,0,26349.817087,120987.621577
4,Toys,Suburban,1,34.789874,9044.445975,2.908800,Snowy,31,3674,44.525732,...,41.486226,4.755281,221,56.588937,0.546467,10967.831730,48.951468,0,10545.399910,152300.675075

In [9]:
prep_df.to_csv("sales_prep.csv",index=False)