In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy.stats import norm
from scipy.stats import ttest_ind
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_regression
import pickle
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [2]:
def selectkbest(indep_X,dep_Y,n):
    test=SelectKBest(f_regression, k=n)
    fit1=test.fit(indep_X,dep_Y)
    selectK_features=fit1.transform(indep_X)
    selected_col=indep_X.columns[fit1.get_support(indices=True)]
    return selectK_features,selected_col

def split_scaler(indep_X,dep_Y):
    X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.30, random_state = 0)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    scy=StandardScaler()
    y_train = scy.fit_transform(y_train)
    y_test = scy.transform(y_test)
    return X_train, X_test, y_train, y_test

def r2_prediction(regressor,X_test,y_test):
    y_pred = regressor.predict(X_test)
    r2=r2_score(y_test,y_pred)
    return r2

def Linear(X_train,y_train,X_test):
    regressor = LinearRegression()
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2

def svm_linear(X_train,y_train,X_test):
    regressor = SVR(kernel = 'linear')
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2 

def svm_NL(X_train,y_train,X_test):
    regressor = SVR(kernel = 'rbf')
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2  

def Decision(X_train,y_train,X_test):
    regressor = DecisionTreeRegressor(random_state = 0)
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2  

def random(X_train,y_train,X_test):
    regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
    regressor.fit(X_train, y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return  r2 

def selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf): 
    dataframe=pd.DataFrame(index=['f_regression'],columns=['Linear','SVMl','SVMnl','Decision','Random'])
    for number,idex in enumerate(dataframe.index):        
        dataframe.loc[idex,'Linear']=acclin[number]       
        dataframe.loc[idex,'SVMl']=accsvml[number]
        dataframe.loc[idex,'SVMnl']=accsvmnl[number]
        dataframe.loc[idex,'Decision']=accdes[number]
        dataframe.loc[idex,'Random']=accrf[number]
    return dataframe

In [3]:
dataset=pd.read_csv('sales_prep.csv',index_col=None)
df=dataset

dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

indep_X=dataset.drop('Sales_Revenue',axis=1)
dep_Y=dataset[['Sales_Revenue']]
dataset

,Holiday_Season,Discount_Percentage,Advertising_Spend,Customer_Rating,Number_of_Employees,Store_Area_sqft,Average_Transaction_Value,Number_of_Customers,Stock_Availability,Competitor_Proximity_km,...,Product_Category_Toys,Store_Location_Suburban,Store_Location_Urban,Weather_Rainy,Weather_Snowy,Weather_Sunny,Marketing_Channel_Email,Marketing_Channel_Radio,Marketing_Channel_Social Media,Marketing_Channel_TV
0,1,8.605530,13786.383758,3.544189,31,2458,271.677695,465,86.561055,5.130822,...,0,0,0,1,0,0,0,1,0,0
1,1,46.276110,18833.572229,2.607173,44,4509,440.936720,935,93.599255,0.723417,...,1,0,0,0,0,0,1,0,0,0
2,0,3.416705,1412.323977,3.311312,36,3235,210.911656,965,54.902892,8.357939,...,0,1,0,0,0,0,0,1,0,0
3,0,21.518737,6733.215078,2.231497,30,4991,246.177510,936,71.815071,7.866605,...,0,0,0,0,1,0,1,0,0,0
4,1,34.789874,9044.445975,2.908800,31,3674,44.525732,100,98.115149,1.935004,...,1,1,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,1,38.678605,4745.394003,4.041313,35,591,69.419798,422,79.797398,0.889412,...,0,0,0,0,1,0,0,1,0,0
796,1,2.202019,2218.967084,3.889646,48,946,65.743360,466,51.568078,8.386519,...,0,1,0,0,0,0,0,0,0,0
797,0,34.666758,4293.433147,1.029568,16,608,211.370698,80,58.513457,0.881128,...,0,0,0,0,0,0,1,0,0,0
798,0,32.411795,16500.766715,3.036542,21,4912,327.440149,417,81.646694,1.004403,...,0,0,1,0,1,0,1,0,0,0
799,0,11.574005,13694.570379,1.557278,19,3739,358.915276,608,70.993519,4.331342,...,0,0,1,0,1,0,0,0,1,0

In [4]:
kbest,selected=selectkbest(indep_X,dep_Y,3)

X_train, X_test, y_train, y_test=split_scaler(indep_X,dep_Y)

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

r2_lin=Linear(X_train,y_train,X_test)
acclin.append(r2_lin)

r2_sl=svm_linear(X_train,y_train,X_test)    
accsvml.append(r2_sl)
    
r2_NL=svm_NL(X_train,y_train,X_test)
accsvmnl.append(r2_NL)
    
r2_d=Decision(X_train,y_train,X_test)
accdes.append(r2_d)
    
r2_r=random(X_train,y_train,X_test)
accrf.append(r2_r)
    
    
result=selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [5]:
#2
result

               Linear      SVMl     SVMnl  Decision    Random
f_regression -0.10826 -0.185727 -0.117819 -1.269625 -0.157963

In [6]:
#3
result

               Linear      SVMl     SVMnl  Decision    Random
f_regression -0.10826 -0.185727 -0.117819 -1.269625 -0.157963

In [7]:
#10
result

               Linear      SVMl     SVMnl  Decision    Random
f_regression -0.10826 -0.185727 -0.117819 -1.269625 -0.157963

In [8]:
selected

Index(['Customer_Rating', 'Weekend_Sales_Percentage', 'Marketing_Channel_TV'], dtype='object')